Repository novaraptur/better-jeopardy, pull requests merged in 2021-07, with the labels that each got.

#16 Component skeleton
  pull_request_template.md
  src/App.js
  src/Components/Answer/Answer.css
  src/Components/Answer/Answer.js
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/Form/Form.css
  src/Components/Form/Form.js
  src/Components/Game/Game.css
  src/Components/Game/Game.js
  src/Components/GameBoard/GameBoard.css
  src/Components/GameBoard/GameBoard.js
  src/Components/PastGames/PastGames.css
  src/Components/PastGames/PastGames.js
  src/Components/Question/Question.css
  src/Components/Question/Question.js
  src/index.js
Labels: React

#18 Component UI
  package-lock.json
  package.json
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Form/Form.js
  src/Components/Game/Game.js
  src/Components/GameBoard/GameBoard.js
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/Tile/Tile.css
  src/Components/Tile/Tile.js
  yarn.lock
Labels: CSS, React, UI

#19 Feature/footer component
  package-lock.json
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.js
Labels: CSS, React, UI

#20 Header Component
  src/Components/App/App.css
  src/Components/Header/Header.css
  src/Components/Header/Header.js
Labels: CSS, React, UI

#24 Question page
  package-lock.json
  src/Components/Answer/Answer.js
  src/Components/Game/.Game.js.swp
  src/Components/Game/Game.js
  src/Components/Question/Question.js
  src/Components/Results/Results.css
  src/Components/Results/Results.js
  src/Components/Tile/Tile.js
  src/utilities/apiCalls.js
Labels: React, UI

#25 Cypress testing
  cypress.json
  cypress/fixtures/allQuestions.json
  cypress/fixtures/example.json
  cypress/fixtures/pastGame.json
  cypress/fixtures/singleQuestion.json
  cypress/fixtures/test.json
  cypress/integration/1-getting-started/todo.spec.js
  cypress/integration/2-advanced-examples/actions.spec.js
  cypress/integration/2-advanced-examples/aliasing.spec.js
  cypress/integration/2-advanced-examples/assertions.spec.js
  cypress/integration/2-advanced-examples/connectors.spec.js
  cypress/integration/2-advanced-examples/cookies.spec.js
  cypress/integration/2-advanced-examples/cypress_api.spec.js
  cypress/integration/2-advanced-examples/files.spec.js
  cypress/integration/2-advanced-examples/local_storage.spec.js
  cypress/integration/2-advanced-examples/location.spec.js
  cypress/integration/2-advanced-examples/misc.spec.js
  cypress/integration/2-advanced-examples/navigation.spec.js
  cypress/integration/2-advanced-examples/network_requests.spec.js
  cypress/integration/2-advanced-examples/querying.spec.js
  cypress/integration/2-advanced-examples/spies_stubs_clocks.spec.js
  cypress/integration/2-advanced-examples/traversal.spec.js
  cypress/integration/2-advanced-examples/utilities.spec.js
  cypress/integration/2-advanced-examples/viewport.spec.js
  cypress/integration/2-advanced-examples/waiting.spec.js
  cypress/integration/2-advanced-examples/window.spec.js
  cypress/integration/App/App.spec.js
  cypress/integration/Game/Game.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/Components/Game/Game.js
  src/Components/GameBoard/GameBoard.js
  src/utilities/apiCalls.js
  yarn.lock
Labels: Testing, documentation

#26 Feature/further game
  package-lock.json
  src/Components/Game/Game.js
  src/Components/GameBoard/GameBoard.css
  src/Components/Question/Question.js
  src/Components/Results/Results.js
  src/Components/Tile/Tile.css
  src/Components/Tile/Tile.js
Labels: React, UI

#29 Feature/refactor question
  src/Components/Game/Game.js
  src/Components/GameBoard/GameBoard.js
Labels: CSS, UI

#28 cypress-questions
  cypress/fixtures/allQuestions.json
  cypress/integration/Game/Game.spec.js
  src/Components/Game/Game.css
  src/Components/Game/Game.js
Labels: React, Testing

#30 Css update
  src/Components/Answer/Answer.css
  src/Components/Answer/Answer.js
  src/Components/App/App.css
  src/Components/Game/Game.css
  src/Components/Game/Game.js
  src/Components/GameBoard/GameBoard.css
  src/Components/GameBoard/GameBoard.js
  src/Components/Header/Header.css
  src/Components/PastGames/PastGames.js
  src/Components/Question/Question.css
  src/Components/Question/Question.js
  src/Components/Results/Results.css
  src/Components/Results/Results.js
  src/Components/Tile/Tile.css
  src/Components/Tile/Tile.js
Labels: CSS, UI

#32 Feature/mobile styling
  src/Components/Answer/Answer.css
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Footer/Footer.css
  src/Components/Game/Game.css
  src/Components/Game/Game.js
  src/Components/GameBoard/GameBoard.css
  src/Components/GameBoard/GameBoard.js
  src/Components/Tile/Tile.css
  src/Components/Tile/Tile.js
Labels: CSS, UI

#33 Feature/implement instructor feedback
  public/index.html
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Footer/Footer.css
  src/Components/Game/Game.js
  src/Components/Header/Header.css
  src/Components/Header/Header.js
Labels: CSS, UI

#34 Remove yarn lock file
  yarn.lock
Labels: bug

#35 Feature/UI answer response
  cypress/integration/Game/Game.spec.js
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Footer/Footer.js
  src/Components/Game/Game.css
  src/Components/Game/Game.js
  src/Components/GameBoard/GameBoard.js
  src/Components/Header/Header.js
  src/Components/Question/Question.js
  src/Components/Tile/Tile.js
Labels: React

#36 Past games page
  src/Components/Game/Game.js
  src/Components/Header/Header.js
  src/Components/PastGames/PastGames.js
  src/Components/Question/Question.js
  src/Components/Results/Results.js
  src/index.js
  src/utilities/apiCalls.js
Labels: API, Express, Postgres, React
